#!/bin/bash

# Allow commits if specific environment variables are set
if [ "$GIT_ALLOW_SECRET_FILES" != "1" ]; then
  echo -e "${YELLOW}Checking for secret files in the staging area...${NO_COLOR}"

  # Get a list of staged files
  STAGED_FILES=$(git diff --cached --name-only)

  # Check each file in SECRET_FILE_NAMES
  for secret_file in "${SECRET_FILE_NAMES[@]}"; do
    if echo "$STAGED_FILES" | grep -q "^${secret_file}$"; then
      # Output error message with limited colors
      echo -e "${RED}Error: Attempt to commit $secret_file detected.${NO_COLOR}"
      echo -e "${YELLOW}Please remove $secret_file from the index by running:${NO_COLOR}"
      echo -e "${YELLOW}git reset HEAD $secret_file${NO_COLOR}"
      echo -e "${YELLOW}and add $secret_file to your .gitignore file if it's not already there.${NO_COLOR}"
      echo -e "${YELLOW}If you really want to commit $secret_file, run:${NO_COLOR}"
      echo -e "${GREEN}GIT_ALLOW_SECRET_FILES=1 git commit -m 'Committing $secret_file'${NO_COLOR}"

      exit 1
    fi
  done
fi